/* 
 * Copyright (C) 2010 hrsldn@gmail.com.  All rights reserved.
 * 
 * This program is free software; you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation; either version 3 of the License, or 
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License 
 * for more details.
 * 
 * You should have received a copy of the GNU General Public License along 
 * with this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 * DownloadEntry.java
 *
 * Created on Jan 2, 2010, 2:08:32 PM
 */
package mudownmanager;

import java.awt.Color;

import org.jdesktop.application.Action;

public class DownloadEntry extends javax.swing.JPanel {

    private int[] rgbBckColor = new int[]{255,255,255};
    
    private boolean stop = false;

    /** Creates new form DownloadEntry */
    public DownloadEntry() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
        setMaximumSize(new java.awt.Dimension(32767, 90));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(545, 90));

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mudownmanager.MuDownManagerApp.class).getContext().getResourceMap(DownloadEntry.class);
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jProgressBar3.setName("jProgressBar3"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(mudownmanager.MuDownManagerApp.class).getContext().getActionMap(DownloadEntry.class, this);
        jButton1.setAction(actionMap.get("stop")); // NOI18N
        jButton1.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar3;
    // End of variables declaration//GEN-END:variables

    public void setRgbBckColor(int[] rgbBckColor) {
       setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
       jPanel1.setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
       jPanel2.setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
    }

    public void setDefaultRgbBckColor () {
       setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
       jPanel1.setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
       jPanel2.setBackground(new Color(rgbBckColor[0], rgbBckColor[1], rgbBckColor[2]));
    }

    public void setBottomText (String text) {
        jLabel6.setText(text);
    }

    public void setTopText (String text) {
        jLabel5.setText(text);
    }

    public void setProgress (int progress) {
        jProgressBar3.setValue(progress);
    }

    @Action
    public void stop () {
    	stop = true;
    }
    
    public boolean isStop() {
		return stop;
	}

    public void setFinished (int timeElapsed) {
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mudownmanager.MuDownManagerApp.class).getContext().getResourceMap(DownloadEntry.class);
        jLabel6.setIcon(resourceMap.getIcon("jLabel6.icon")); // NOI18N
        jLabel6.setText("Download finished.");
        jButton1.setEnabled(false);
    }

    public void setFailed (int timeElapsed) {
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mudownmanager.MuDownManagerApp.class).getContext().getResourceMap(DownloadEntry.class);
        jLabel6.setIcon(resourceMap.getIcon("jLabel6.icon.failed")); // NOI18N
        jLabel6.setText("Download failed.");
        jButton1.setEnabled(false);
    }
    
    public void setStopped () {
    	org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mudownmanager.MuDownManagerApp.class).getContext().getResourceMap(DownloadEntry.class);
        jLabel6.setIcon(resourceMap.getIcon("jButton1.icon")); // NOI18N
        jLabel6.setText("Download stopped.");
        jButton1.setEnabled(false);
    }
}
